FE = input("Put your Foundation English score: ")
GB = input("Put your General Business score : ")
ICS = input("Put your Introduction to Computer Systems score ")
CP = input("Put youur Computer Programming score : ")
print("--- Your Score ---")
print("Foundation English : " + FE)
print("General Business : " + GB)
print("Introduction to Computer Systems : " + ICS)
print("Computer Programming : " + CP)